---
name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'master'
      - '*-stable'


concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  puppet:
    name: Puppet
    uses: voxpupuli/gha-puppet/.github/workflows/basic.yml@v3
    with:
      rubocop: false
